DROP TABLE IF EXISTS user;
CREATE TABLE user (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ON CONFLICT FAIL,
	name TEXT NOT NULL,
	hash TEXT NOT NULL,
	unique (name)
);

DROP TABLE IF EXISTS domain;
CREATE TABLE domain (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ON CONFLICT FAIL,
	name TEXT NOT NULL,
	address TEXT NOT NULL,
	user TEXT NOT NULL,
	ttl INTEGER,
	timestamp INTEGER DEFAULT ( datetime('now') ),
	FOREIGN KEY (user) REFERENCES user(name) ON DELETE CASCADE
);
